# Generated by Django 3.1.3 on 2021-01-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='jwt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
