# Generated by Django 3.1.4 on 2021-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210128_0719'),
        ('Blog', '0002_auto_20210118_1302'),
    ]

    operations = [
    ]
